version: "3.7"

networks:
  odoonet:

volumes:
  odoo-data:
  odoo-modules:
  psql:

services:
  odoo:
    image: car_workshop:latest
    env_file: .env
    build: .
    restart: unless-stopped

    ports: ["8069:8069", "8072:8072"]

    volumes:
      # Named volumes
      - odoo-data:${ODOO_DATA_DIR}
      - odoo-modules:${ODOO_EXTRA_ADDONS}:cached
    depends_on:
      - db
    command: ["/opt/odoo/odoo-bin", "-u", "car_workshop"]
    networks:
      odoonet:
  # ------------------------
  db:
    image: postgres:${PSQL_VERSION}
    restart: unless-stopped
    volumes:
      - psql:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata

    networks:
      odoonet:
